package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"fmt"
	"learning/internal/graphql/models"
)

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input models.CreateProductInput) (*models.CreateProductPayload, error) {
	panic(fmt.Errorf("not implemented: CreateProduct - createProduct"))
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, input models.UpdateProductInput) (*models.UpdateProductPayload, error) {
	panic(fmt.Errorf("not implemented: UpdateProduct - updateProduct"))
}

// DeleteProduct is the resolver for the deleteProduct field.
func (r *mutationResolver) DeleteProduct(ctx context.Context, input models.DeleteProductInput) (*models.DeleteProductPayload, error) {
	panic(fmt.Errorf("not implemented: DeleteProduct - deleteProduct"))
}

// UpdateProductStock is the resolver for the updateProductStock field.
func (r *mutationResolver) UpdateProductStock(ctx context.Context, input models.UpdateProductStockInput) (*models.UpdateProductStockPayload, error) {
	panic(fmt.Errorf("not implemented: UpdateProductStock - updateProductStock"))
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, id string) (*models.Product, error) {
	panic(fmt.Errorf("not implemented: Product - product"))
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, first *int, after *string, last *int, before *string, category *string, search *string, inStock *bool) (*models.ProductConnection, error) {
	panic(fmt.Errorf("not implemented: Products - products"))
}

// ProductCategories is the resolver for the productCategories field.
func (r *queryResolver) ProductCategories(ctx context.Context) ([]*models.ProductCategory, error) {
	panic(fmt.Errorf("not implemented: ProductCategories - productCategories"))
}

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *productResolver) IsInStock(ctx context.Context, obj *product.Product) (bool, error) {
	panic(fmt.Errorf("not implemented: IsInStock - isInStock"))
}
func (r *productResolver) StockStatus(ctx context.Context, obj *product.Product) (models.StockStatus, error) {
	panic(fmt.Errorf("not implemented: StockStatus - stockStatus"))
}
func (r *Resolver) Product() generated.ProductResolver { return &productResolver{r} }
type productResolver struct{ *Resolver }
*/
